export { default as Tablero } from './Tablero';
export { default as Kanban } from './Kanban';
export { default as Competencias } from './Competencias';
export { default as Profesores} from './Profesores';
export { default as Editor } from './Editor';
export { default as Estudiantes } from './Estudiantes';
export { default as ColorPicker } from './ColorPicker';
export { default as Calendar } from './Calendar';
export { default as Calificacion } from './Calificacion';
export { default as Financial } from './Charts/Financial';
export { default as Area } from './Charts/Area';
export { default as Bar } from './Charts/Bar';
export { default as ColorMapping } from './Charts/ColorMapping';
export { default as Line } from './Charts/Line';
export { default as Pie } from './Charts/Pie';
export { default as Pyramid } from './Charts/Pyramid';
export { default as Stacked } from './Charts/Stacked';